### ISSUE TITLE
Couldn't reference directories..

### ISSUE THREAD

**Issue by SeYoungKim** [trinhan/crc-ihc-classification#2]
Hello!

In R codes for training classifier with AMC data, directory names didn't match..

1. In RunClassifier.R file, "AMC_set/" is passed to ReadFromCSV function, but seems like it should have been "AMC_data/"

2. Isn't it that, at ImageAnalysisScripts/classifier/AMC_mapping directory, "AMC_map.csv" is correct instead of "C1_map.csv"? Because the code looks for this file with a name which is read from "AMC_mapping/C1_slide_no.csv" file like below... 
```
idx2 = grep(Slide_No[i, 1], MFiles)
mapping = read.csv(sprintf('%s%s', mapdir, MFiles[idx2]), header=F)
``` 
And in "classifier/AMC_mapping/C1_slide_no.csv" file, "AMC_map" is written(TMA_slide_Number value)

So the code tries to find a file whose name is "AMC_map" and fails...

**Comment by trinhan** [comment]
RunClassifier.R has been updated with directories

**Comment by SeYoungKim** [comment]
Thank you. Now it's working!
