### ISSUE TITLE
About Compress.Scores

### ISSUE THREAD

**Issue by SeYoungKim** [trinhan/crc-ihc-classification#3]
Hello!

In RunClassifier.R file, it is using Compress.Scores function but couldn't find it...

```
Error in Compress.Scores(output, AMCdata.train$PatID$Pat, 2, 0.6) : 
  could not find function "Compress.Scores"
```

this error occured at

```
PatClasses = Compress.Scores(output, AMCdata.train$PatID$Pat, 2, 0.6)
```

I've imported like below..

```
library(gsubfn)
library(randomForest)
library(e1071)
library(nnet)
library(rpart)
library(survival)
library(RColorBrewer)
library(preprocessCore)
library(ggplot2)
library(reshape2)
library(MASS)
library(scatterplot3d)

source("classifier_functions.R")
```

Is there something I missed...? 

It seems like rows are categorized in the function with the cutoff value 60...

Any help will be appreciated.

Thank you

**Comment by trinhan** [comment]
classifier_functions.R has been updated

**Comment by SeYoungKim** [comment]
Thank you I could see the result of the program..!
